apiVersion: kubermatic.k8s.io/v1
kind: Seed
metadata:
  name: kubermatic
  namespace: kubermatic
spec:
  country: DE
  datacenters:
    frankfurt:
      country: "DE"
      location: "eu-central-1"
      spec:
        aws:
          region: "eu-central-1"
  mla:
    user_cluster_mla_enabled: true
  kubeconfig:
    name: kubeconfig-cluster
    namespace: kubermatic
