iap:
    oidc_issuer_url: https://usermla.lab.kubermatic.io/dex
    deployments:
        grafana:
            name: grafana
            replicas: 1
            client_id: mla-grafana
            client_secret: ZxF5nq1yohcdJtVj
            encryption_key: o7LGDgbxu2XOofDu
            config:
                scope: groups openid email
                email_domains:
                    - '*'
                ## do not route health endpoint through the proxy
                skip_auth_regex:
                    - /api/health
                ## auto-register users based on their email address
                ## Grafana is configured to look for the X-Forwarded-Email header
                pass_user_headers: true
            upstream_service: grafana.mla.svc.cluster.local
            upstream_port: 80
            ingress:
                host: grafana-user.kubermatic.usermla.lab.kubermatic.io
        alertmanager:
            name: alertmanager
            replicas: 1
            client_id: mla-alertmanager
            client_secret: MKvrKK7zU2Yp9VvZ
            encryption_key: tCrBocSVte3vaSyl
            config:
                scope: groups openid email
                email_domains:
                    - '*'
                ## do not route health endpoint through the proxy
                skip_auth_regex:
                    - /api/health
                ## auto-register users based on their email address
                ## Grafana is configured to look for the X-Forwarded-Email header
                pass_user_headers: true
            upstream_service: alertmanager-proxy.mla.svc.cluster.local
            upstream_port: 8080
            ingress:
                host: alertmanager-user.kubermatic.usermla.lab.kubermatic.io
